name: stafflink
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  shared_preferences: ^2.2.2 # Atau ^2.1.1, pilih versi yang ingin Anda gunakan
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  http: ^1.4.0
  file_picker: ^10.1.9
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png